CREATE TABLE `backlink_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`sourceUrl` text NOT NULL,
	`sourceDomain` varchar(255) NOT NULL,
	`sourceDA` int,
	`sourceDR` int,
	`sourceSpamScore` int,
	`sourceTrustFlow` int,
	`targetUrl` text NOT NULL,
	`anchorText` varchar(500),
	`linkType` enum('dofollow','nofollow','ugc','sponsored') NOT NULL DEFAULT 'dofollow',
	`blSourceType` enum('pbn','guest_post','web2','forum','comment','social','directory','edu','gov','press_release','parasite','tier2','other') NOT NULL DEFAULT 'other',
	`blStatus` enum('active','lost','broken','deindexed','pending','building') NOT NULL DEFAULT 'active',
	`qualityScore` int,
	`isIndexed` boolean DEFAULT false,
	`indexedAt` timestamp,
	`firstSeenAt` timestamp NOT NULL DEFAULT (now()),
	`lastCheckedAt` timestamp,
	`lostAt` timestamp,
	`aiNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `backlink_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `rank_tracking` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`keyword` varchar(500) NOT NULL,
	`searchEngine` varchar(32) NOT NULL DEFAULT 'google',
	`country` varchar(8) NOT NULL DEFAULT 'US',
	`device` enum('desktop','mobile') NOT NULL DEFAULT 'desktop',
	`position` int,
	`previousPosition` int,
	`bestPosition` int,
	`positionChange` int,
	`serpUrl` text,
	`serpTitle` text,
	`serpSnippet` text,
	`serpFeatures` json,
	`searchVolume` int,
	`keywordDifficulty` int,
	`cpc` decimal(8,2),
	`rankTrend` enum('rising','stable','falling','new','lost') DEFAULT 'new',
	`aiInsight` text,
	`trackedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `rank_tracking_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seo_actions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`seoActionType` enum('analysis','keyword_research','onpage_audit','backlink_build','content_create','pbn_post','tier2_build','social_signal','index_request','disavow','strategy_update','rank_check','competitor_analysis','algorithm_check','risk_assessment') NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`seoActionStatus` enum('pending','running','completed','failed','skipped') NOT NULL DEFAULT 'pending',
	`result` json,
	`actionImpact` enum('positive','neutral','negative','unknown') DEFAULT 'unknown',
	`executedAt` timestamp,
	`completedAt` timestamp,
	`errorMessage` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `seo_actions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seo_projects` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`domain` varchar(255) NOT NULL,
	`name` varchar(255),
	`niche` varchar(255),
	`targetKeywords` json,
	`seoStrategy` enum('grey_hat','black_hat','aggressive_grey','pbn_focused','tiered_links','parasite_seo') NOT NULL DEFAULT 'grey_hat',
	`seoProjectStatus` enum('setup','analyzing','active','paused','completed','penalized') NOT NULL DEFAULT 'setup',
	`currentDA` int,
	`currentDR` int,
	`currentSpamScore` int,
	`currentBacklinks` int,
	`currentReferringDomains` int,
	`currentTrustFlow` int,
	`currentCitationFlow` int,
	`currentOrganicTraffic` int,
	`currentOrganicKeywords` int,
	`daTrend` int DEFAULT 0,
	`drTrend` int DEFAULT 0,
	`backlinkTrend` int DEFAULT 0,
	`trafficTrend` int DEFAULT 0,
	`overallTrend` enum('improving','stable','declining','critical') DEFAULT 'stable',
	`aiHealthScore` int,
	`aiRiskLevel` enum('low','medium','high','critical') DEFAULT 'medium',
	`aiStrategy` text,
	`aiLastAnalysis` text,
	`aiNextActions` json,
	`autoBacklink` boolean NOT NULL DEFAULT true,
	`autoContent` boolean NOT NULL DEFAULT false,
	`autoPbn` boolean NOT NULL DEFAULT false,
	`aggressiveness` int NOT NULL DEFAULT 5,
	`monthlyBudget` decimal(12,2) DEFAULT '0',
	`totalBacklinksBuilt` int DEFAULT 0,
	`totalContentCreated` int DEFAULT 0,
	`totalActionsExecuted` int DEFAULT 0,
	`lastAnalyzedAt` timestamp,
	`lastActionAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seo_projects_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seo_snapshots` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`da` int,
	`dr` int,
	`spamScore` int,
	`backlinks` int,
	`referringDomains` int,
	`trustFlow` int,
	`citationFlow` int,
	`organicTraffic` int,
	`organicKeywords` int,
	`dofollowLinks` int,
	`nofollowLinks` int,
	`pbnLinks` int,
	`guestPostLinks` int,
	`web2Links` int,
	`otherLinks` int,
	`aiHealthScore` int,
	`aiRiskLevel` varchar(16),
	`snapshotDate` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `seo_snapshots_id` PRIMARY KEY(`id`)
);
