CREATE TABLE `ai_attack_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`targetDomain` varchar(255) NOT NULL,
	`targetIp` varchar(64),
	`serverType` varchar(128),
	`serverVersion` varchar(64),
	`cms` varchar(64),
	`cmsVersion` varchar(32),
	`language` varchar(32),
	`os` varchar(64),
	`waf` varchar(64),
	`wafStrength` varchar(16),
	`hostingProvider` varchar(128),
	`controlPanel` varchar(64),
	`sslEnabled` boolean,
	`redirectUrl` varchar(512),
	`method` varchar(128) NOT NULL,
	`filename` varchar(255),
	`uploadPath` varchar(512),
	`contentType` varchar(128),
	`httpMethod` varchar(16),
	`bypassTechnique` varchar(255),
	`payloadType` varchar(64),
	`success` boolean NOT NULL DEFAULT false,
	`statusCode` int,
	`errorMessage` text,
	`fileVerified` boolean DEFAULT false,
	`redirectVerified` boolean DEFAULT false,
	`uploadedUrl` varchar(512),
	`durationMs` int,
	`aiReasoning` text,
	`aiConfidence` int,
	`iteration` int,
	`preAnalysisData` json,
	`pipelineType` varchar(32),
	`sessionId` varchar(64),
	`historyCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_attack_history_id` PRIMARY KEY(`id`)
);
