CREATE TABLE `seo_agent_tasks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`projectId` int NOT NULL,
	`userId` int NOT NULL,
	`seoTaskType` enum('domain_analysis','keyword_research','keyword_gap_analysis','onpage_audit','content_plan','content_create','content_publish_wp','backlink_plan','backlink_build_pbn','backlink_build_web2','backlink_build_guest','backlink_build_social','backlink_tier2','index_request','rank_check','competitor_spy','wp_optimize','wp_fix_issues','schema_markup','internal_linking','strategy_review','risk_assessment','report_generate') NOT NULL,
	`seoTaskTitle` varchar(500) NOT NULL,
	`seoTaskDescription` text,
	`seoTaskStatus` enum('queued','running','completed','failed','skipped') NOT NULL DEFAULT 'queued',
	`seoTaskPriority` int NOT NULL DEFAULT 5,
	`dependsOn` json,
	`seoTaskResult` json,
	`seoTaskError` text,
	`seoTaskAiReasoning` text,
	`seoTaskAiConfidence` int,
	`scheduledFor` timestamp,
	`seoTaskStartedAt` timestamp,
	`seoTaskCompletedAt` timestamp,
	`seoTaskDurationMs` int,
	`seoTaskCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`seoTaskUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seo_agent_tasks_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `seo_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contentProjectId` int NOT NULL,
	`contentUserId` int NOT NULL,
	`contentTitle` varchar(500) NOT NULL,
	`contentSlug` varchar(500),
	`contentBody` text NOT NULL,
	`contentExcerpt` text,
	`contentTargetKeyword` varchar(255),
	`contentSecondaryKeywords` json,
	`contentMetaTitle` varchar(255),
	`contentMetaDescription` text,
	`contentWordCount` int NOT NULL DEFAULT 0,
	`contentSeoScore` int,
	`contentReadabilityScore` int,
	`contentPublishStatus` enum('draft','ready','published','failed') NOT NULL DEFAULT 'draft',
	`wpPostId` int,
	`wpUrl` text,
	`contentPublishedAt` timestamp,
	`contentAiModel` varchar(64),
	`contentAiPrompt` text,
	`contentCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`contentUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `seo_content_id` PRIMARY KEY(`id`)
);
