CREATE TABLE `scan_results` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scanId` int NOT NULL,
	`resultUserId` int NOT NULL,
	`resultDomain` varchar(255) NOT NULL,
	`totalTests` int NOT NULL DEFAULT 0,
	`totalFindings` int NOT NULL DEFAULT 0,
	`criticalCount` int NOT NULL DEFAULT 0,
	`highCount` int NOT NULL DEFAULT 0,
	`mediumCount` int NOT NULL DEFAULT 0,
	`lowCount` int NOT NULL DEFAULT 0,
	`infoCount` int NOT NULL DEFAULT 0,
	`exploitableCount` int NOT NULL DEFAULT 0,
	`findings` json,
	`newFindings` int NOT NULL DEFAULT 0,
	`resolvedFindings` int NOT NULL DEFAULT 0,
	`newFindingsDetail` json,
	`resolvedFindingsDetail` json,
	`scanDurationMs` int,
	`resultStatus` enum('completed','partial','failed') NOT NULL DEFAULT 'completed',
	`scanErrorMessage` text,
	`telegramSent` boolean DEFAULT false,
	`resultCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `scan_results_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduled_scans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scanUserId` int NOT NULL,
	`scanDomain` varchar(255) NOT NULL,
	`scanFrequency` enum('daily','weekly','biweekly','monthly') NOT NULL DEFAULT 'weekly',
	`scheduleDays` json,
	`scheduleHour` int NOT NULL DEFAULT 3,
	`scanAttackTypes` json,
	`enableComprehensive` boolean NOT NULL DEFAULT true,
	`enableIndirect` boolean NOT NULL DEFAULT true,
	`enableShellless` boolean NOT NULL DEFAULT true,
	`enableDns` boolean NOT NULL DEFAULT false,
	`telegramAlert` boolean NOT NULL DEFAULT true,
	`alertMinSeverity` enum('critical','high','medium','low','info') NOT NULL DEFAULT 'high',
	`scanEnabled` boolean NOT NULL DEFAULT true,
	`lastRunAt` timestamp,
	`nextRunAt` timestamp,
	`lastRunStatus` enum('success','partial','failed','running'),
	`totalRuns` int NOT NULL DEFAULT 0,
	`scanCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`scanUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scheduled_scans_id` PRIMARY KEY(`id`)
);
