CREATE TABLE `remediation_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`scanId` int,
	`scanResultId` int,
	`remDomain` varchar(255) NOT NULL,
	`remVector` varchar(128) NOT NULL,
	`remCategory` varchar(64) NOT NULL,
	`remSeverity` varchar(16) NOT NULL,
	`remFinding` text,
	`fixStrategy` varchar(64) NOT NULL,
	`fixAction` varchar(128) NOT NULL,
	`fixDetail` text,
	`revertible` boolean NOT NULL DEFAULT false,
	`revertAction` text,
	`beforeState` json,
	`afterState` json,
	`remStatus` enum('applied','reverted','revert_failed','expired') NOT NULL DEFAULT 'applied',
	`revertedAt` timestamp,
	`revertDetail` text,
	`appliedAt` timestamp NOT NULL DEFAULT (now()),
	`remUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `remediation_history_id` PRIMARY KEY(`id`)
);
