CREATE TABLE `ai_decisions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`decisionCycle` int NOT NULL,
	`decisionPhase` varchar(32) NOT NULL,
	`decisionSubsystem` varchar(32) NOT NULL,
	`decision` varchar(255) NOT NULL,
	`decisionReasoning` text NOT NULL,
	`decisionConfidence` int NOT NULL DEFAULT 0,
	`decisionInputData` json,
	`decisionOutputData` json,
	`tasksCreated` int NOT NULL DEFAULT 0,
	`impactLevel` varchar(16) NOT NULL DEFAULT 'medium',
	`decisionCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_decisions_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_metrics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`metricDate` timestamp NOT NULL,
	`metricType` varchar(16) NOT NULL DEFAULT 'daily',
	`cyclesRun` int NOT NULL DEFAULT 0,
	`tasksQueued` int NOT NULL DEFAULT 0,
	`metricsTasksCompleted` int NOT NULL DEFAULT 0,
	`metricsTasksFailed` int NOT NULL DEFAULT 0,
	`decisionsCount` int NOT NULL DEFAULT 0,
	`seoActions` int NOT NULL DEFAULT 0,
	`attackActions` int NOT NULL DEFAULT 0,
	`pbnActions` int NOT NULL DEFAULT 0,
	`discoveryActions` int NOT NULL DEFAULT 0,
	`rankActions` int NOT NULL DEFAULT 0,
	`domainsProcessed` int NOT NULL DEFAULT 0,
	`backlinksBuilt` int NOT NULL DEFAULT 0,
	`contentCreated` int NOT NULL DEFAULT 0,
	`ranksImproved` int NOT NULL DEFAULT 0,
	`attacksSucceeded` int NOT NULL DEFAULT 0,
	`targetsDiscovered` int NOT NULL DEFAULT 0,
	`metricsCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_metrics_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_orchestrator_state` (
	`id` int AUTO_INCREMENT NOT NULL,
	`orchStatus` enum('running','paused','stopped','error') NOT NULL DEFAULT 'stopped',
	`currentCycle` int NOT NULL DEFAULT 0,
	`totalCycles` int NOT NULL DEFAULT 0,
	`lastCycleAt` timestamp,
	`nextCycleAt` timestamp,
	`cycleIntervalMinutes` int NOT NULL DEFAULT 30,
	`seoEnabled` boolean NOT NULL DEFAULT true,
	`attackEnabled` boolean NOT NULL DEFAULT false,
	`pbnEnabled` boolean NOT NULL DEFAULT true,
	`discoveryEnabled` boolean NOT NULL DEFAULT false,
	`rankTrackingEnabled` boolean NOT NULL DEFAULT true,
	`autobidEnabled` boolean NOT NULL DEFAULT false,
	`orchAggressiveness` enum('conservative','balanced','aggressive','maximum') NOT NULL DEFAULT 'balanced',
	`maxConcurrentTasks` int NOT NULL DEFAULT 3,
	`maxDailyActions` int NOT NULL DEFAULT 100,
	`todayActions` int NOT NULL DEFAULT 0,
	`totalTasksCompleted` int NOT NULL DEFAULT 0,
	`totalTasksFailed` int NOT NULL DEFAULT 0,
	`totalDecisions` int NOT NULL DEFAULT 0,
	`orchSuccessRate` decimal(5,2) DEFAULT '0',
	`aiWorldState` json,
	`aiPriorities` json,
	`aiLearnings` json,
	`orchCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`orchUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_orchestrator_state_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_task_queue` (
	`id` int AUTO_INCREMENT NOT NULL,
	`taskType` varchar(64) NOT NULL,
	`taskSubsystem` varchar(32) NOT NULL,
	`taskTitle` varchar(255) NOT NULL,
	`taskDescription` text,
	`taskTargetDomain` varchar(255),
	`taskProjectId` int,
	`taskPriority` enum('critical','high','medium','low') NOT NULL DEFAULT 'medium',
	`taskStatus` enum('queued','running','completed','failed','cancelled','skipped') NOT NULL DEFAULT 'queued',
	`taskAiReasoning` text,
	`taskStartedAt` timestamp,
	`taskCompletedAt` timestamp,
	`taskResult` json,
	`taskError` text,
	`taskRetryCount` int NOT NULL DEFAULT 0,
	`taskMaxRetries` int NOT NULL DEFAULT 3,
	`dependsOnTaskId` int,
	`scheduledFor` timestamp,
	`taskCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`taskUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ai_task_queue_id` PRIMARY KEY(`id`)
);
