CREATE TABLE `exploit_history` (
	`id` int AUTO_INCREMENT NOT NULL,
	`targetDomain` varchar(512) NOT NULL,
	`targetUrl` varchar(1024) NOT NULL,
	`cveId` varchar(32),
	`exploitType` varchar(64) NOT NULL,
	`exploitSource` varchar(32) NOT NULL,
	`cms` varchar(32),
	`component` varchar(128),
	`success` boolean NOT NULL DEFAULT false,
	`uploadedUrl` varchar(1024),
	`redirectVerified` boolean NOT NULL DEFAULT false,
	`httpStatus` int,
	`errorMessage` text,
	`wafDetected` varchar(64),
	`wafBypassed` boolean NOT NULL DEFAULT false,
	`evasionTechnique` varchar(128),
	`payloadHash` varchar(64),
	`payloadSize` int,
	`durationMs` int,
	`pipelineRunId` varchar(64),
	`attackPhase` varchar(32),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `exploit_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `waf_detections` (
	`id` int AUTO_INCREMENT NOT NULL,
	`targetDomain` varchar(512) NOT NULL,
	`targetUrl` varchar(1024) NOT NULL,
	`wafName` varchar(64),
	`wafVendor` varchar(64),
	`confidence` varchar(16),
	`strength` varchar(16),
	`blocksXss` boolean NOT NULL DEFAULT false,
	`blocksSqli` boolean NOT NULL DEFAULT false,
	`blocksFileUpload` boolean NOT NULL DEFAULT false,
	`blocksPathTraversal` boolean NOT NULL DEFAULT false,
	`blocksCommandInjection` boolean NOT NULL DEFAULT false,
	`blocksRateLimit` boolean NOT NULL DEFAULT false,
	`detectionMethods` json,
	`evasionRecommendations` json,
	`rawHeaders` json,
	`rawFingerprints` json,
	`pipelineRunId` varchar(64),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `waf_detections_id` PRIMARY KEY(`id`)
);
