CREATE TABLE `cms_attack_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`capCms` varchar(64) NOT NULL,
	`capCmsVersion` varchar(32),
	`capMethodRankings` json,
	`capCommonWafs` json,
	`capTotalAttacks` int NOT NULL DEFAULT 0,
	`capOverallSuccessRate` decimal(5,2) NOT NULL DEFAULT '0',
	`capBestMethod` varchar(128),
	`capBestMethodRate` decimal(5,2),
	`capWorstMethod` varchar(128),
	`capAiPlaybook` text,
	`capAiPlaybookConfidence` int,
	`capUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`capCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `cms_attack_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `learned_patterns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`lpPatternType` varchar(64) NOT NULL,
	`lpPatternKey` varchar(255) NOT NULL,
	`lpTotalAttempts` int NOT NULL DEFAULT 0,
	`lpTotalSuccesses` int NOT NULL DEFAULT 0,
	`lpSuccessRate` decimal(5,2) NOT NULL DEFAULT '0',
	`lpAvgDurationMs` int NOT NULL DEFAULT 0,
	`lpLastSuccessAt` timestamp,
	`lpLastFailureAt` timestamp,
	`lpAiInsight` text,
	`lpAiRecommendation` text,
	`lpConfidenceScore` int NOT NULL DEFAULT 0,
	`lpSampleSuccessContexts` json,
	`lpSampleFailureContexts` json,
	`lpBestPayloadMods` json,
	`lpBestWafBypasses` json,
	`lpBestAttackPaths` json,
	`lpUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`lpCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `learned_patterns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `strategy_outcome_logs` (
	`id` int AUTO_INCREMENT NOT NULL,
	`targetDomain` varchar(255) NOT NULL,
	`solCms` varchar(64),
	`solCmsVersion` varchar(32),
	`solServerType` varchar(128),
	`solPhpVersion` varchar(32),
	`solWafDetected` varchar(64),
	`solWafStrength` varchar(16),
	`solVulnScore` int,
	`solMethod` varchar(128) NOT NULL,
	`solExploitType` varchar(128),
	`solPayloadType` varchar(64),
	`solWafBypassUsed` json,
	`solPayloadMods` json,
	`solAttackPath` varchar(512),
	`solAttemptNumber` int NOT NULL DEFAULT 1,
	`solIsRetry` boolean NOT NULL DEFAULT false,
	`solPreviousMethods` json,
	`solSuccess` boolean NOT NULL DEFAULT false,
	`solHttpStatus` int,
	`solErrorCategory` varchar(64),
	`solErrorMessage` text,
	`solFilesPlaced` int NOT NULL DEFAULT 0,
	`solRedirectVerified` boolean NOT NULL DEFAULT false,
	`solDurationMs` int,
	`solAiFailureCategory` varchar(64),
	`solAiReasoning` text,
	`solAiConfidence` int,
	`solAiEstimatedSuccess` int,
	`solSessionId` int,
	`solAgenticSessionId` int,
	`solCreatedAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `strategy_outcome_logs_id` PRIMARY KEY(`id`)
);
