CREATE TABLE `keyword_performance` (
	`id` int AUTO_INCREMENT NOT NULL,
	`keyword` varchar(500) NOT NULL,
	`targetDomain` varchar(512) NOT NULL,
	`parasiteDomain` varchar(512),
	`agenticSessionId` int,
	`attackMethod` varchar(64),
	`attackedAt` timestamp,
	`rankBefore` int,
	`rankAfter1h` int,
	`rankAfter24h` int,
	`rankAfter7d` int,
	`rankAfter30d` int,
	`currentRank` int,
	`bestRank` int,
	`rankImprovement` int,
	`isOnPage1` boolean NOT NULL DEFAULT false,
	`isInTop3` boolean NOT NULL DEFAULT false,
	`estimatedTraffic` int NOT NULL DEFAULT 0,
	`estimatedValue` decimal(10,2),
	`performanceScore` int NOT NULL DEFAULT 0,
	`perfStatus` enum('pending','tracking','peaked','stable','lost','completed') NOT NULL DEFAULT 'pending',
	`nextCheckAt` timestamp,
	`lastCheckedAt` timestamp,
	`totalChecks` int NOT NULL DEFAULT 0,
	`perfCategory` varchar(64),
	`perfSearchVolume` int,
	`perfKeywordDifficulty` int,
	`perfCpc` decimal(8,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `keyword_performance_id` PRIMARY KEY(`id`)
);
