CREATE TABLE `tracked_content` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contentKey` varchar(128) NOT NULL,
	`url` text NOT NULL,
	`title` varchar(500) NOT NULL,
	`keyword` varchar(500) NOT NULL,
	`tcPlatform` enum('telegraph','web2.0','target','other') NOT NULL DEFAULT 'other',
	`originalContent` text,
	`currentContent` text,
	`telegraphToken` varchar(255),
	`telegraphPath` varchar(255),
	`tcDomain` varchar(512) NOT NULL,
	`tcDeployedAt` timestamp NOT NULL DEFAULT (now()),
	`tcLastRefreshedAt` timestamp NOT NULL DEFAULT (now()),
	`tcRefreshCount` int NOT NULL DEFAULT 0,
	`tcCurrentRank` int,
	`tcStalenessScore` int NOT NULL DEFAULT 0,
	`tcPriority` int NOT NULL DEFAULT 5,
	`tcStatus` enum('fresh','aging','stale','refreshing','error') NOT NULL DEFAULT 'fresh',
	`tcSourceEngine` varchar(64),
	`tcProjectId` int,
	`tcCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`tcUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `tracked_content_id` PRIMARY KEY(`id`),
	CONSTRAINT `tracked_content_contentKey_unique` UNIQUE(`contentKey`)
);
