CREATE TABLE `wp_themes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(128) NOT NULL,
	`name` varchar(255) NOT NULL,
	`category` enum('slots','lottery','baccarat') NOT NULL,
	`description` text,
	`primaryColor` varchar(32) NOT NULL,
	`secondaryColor` varchar(32) NOT NULL,
	`accentColor` varchar(32) NOT NULL,
	`bgColor` varchar(32) NOT NULL,
	`textColor` varchar(32) NOT NULL,
	`fontHeading` varchar(128) NOT NULL,
	`fontBody` varchar(128) NOT NULL,
	`layoutStyle` varchar(64) NOT NULL,
	`heroStyle` varchar(64) NOT NULL,
	`seoSchemaTypes` json,
	`seoFeatures` json,
	`mobileNavStyle` varchar(64) NOT NULL,
	`mobileFeatures` json,
	`themeFiles` json,
	`previewHtml` text,
	`version` varchar(16) NOT NULL DEFAULT '1.0.0',
	`tags` json,
	`isActive` boolean NOT NULL DEFAULT true,
	`deployCount` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `wp_themes_id` PRIMARY KEY(`id`),
	CONSTRAINT `wp_themes_slug_unique` UNIQUE(`slug`)
);
