CREATE TABLE `attack_strategy_cache` (
	`id` int AUTO_INCREMENT NOT NULL,
	`ascDomainPattern` varchar(255),
	`ascServerType` varchar(128),
	`ascCms` varchar(64),
	`ascWaf` varchar(64),
	`ascWafStrength` varchar(16),
	`ascHosting` varchar(128),
	`ascRecommendedMode` varchar(64) NOT NULL,
	`ascRecommendedMethods` json,
	`ascAvoidMethods` json,
	`ascTotalAttempts` int NOT NULL DEFAULT 0,
	`ascSuccessCount` int NOT NULL DEFAULT 0,
	`ascFailureCount` int NOT NULL DEFAULT 0,
	`ascSuccessRate` int NOT NULL DEFAULT 0,
	`ascAvgDurationMs` int,
	`ascConfidence` int NOT NULL DEFAULT 50,
	`ascAiReasoning` text,
	`ascLastSuccessMethod` varchar(128),
	`ascLastFailureReason` text,
	`ascLearnedInsights` json,
	`ascCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`ascUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `attack_strategy_cache_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `failure_analytics` (
	`id` int AUTO_INCREMENT NOT NULL,
	`faDomain` varchar(255) NOT NULL,
	`faMode` varchar(64) NOT NULL,
	`faServerType` varchar(128),
	`faCms` varchar(64),
	`faCmsVersion` varchar(32),
	`faWaf` varchar(64),
	`faWafStrength` varchar(16),
	`faHosting` varchar(128),
	`faMethodsTried` json,
	`faTotalMethods` int NOT NULL DEFAULT 0,
	`faTimeoutCount` int NOT NULL DEFAULT 0,
	`faErrorCount` int NOT NULL DEFAULT 0,
	`faTotalDurationMs` int,
	`faAiAnalysis` text,
	`faFailurePattern` varchar(128),
	`faNewStrategies` json,
	`faStrategiesGenerated` int NOT NULL DEFAULT 0,
	`faRetryAttempted` boolean NOT NULL DEFAULT false,
	`faRetrySuccess` boolean NOT NULL DEFAULT false,
	`faRetryMethod` varchar(128),
	`faRetryDurationMs` int,
	`faCreatedAt` timestamp NOT NULL DEFAULT (now()),
	`faUpdatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `failure_analytics_id` PRIMARY KEY(`id`)
);
