export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  shodanApiKey: process.env.SHODAN_API_KEY ?? "",
  mozAccessId: process.env.MOZ_ACCESS_ID ?? "",
  mozSecretKey: process.env.MOZ_SECRET_KEY ?? "",
  ahrefsApiKey: process.env.AHREFS_API_KEY ?? "",
  serpApiKey: process.env.SERPAPI_KEY_DEV ?? "",
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? "",
  telegramChatId: process.env.TELEGRAM_CHAT_ID ?? "",
  telegramChatId2: process.env.TELEGRAM_CHAT_ID_2 ?? "",
  telegramChatId3: process.env.TELEGRAM_CHAT_ID_3 ?? "",
  // Telegram Webhook
  telegramWebhookSecret: process.env.TELEGRAM_WEBHOOK_SECRET ?? "",
  // Fallback LLM providers
  openaiApiKey: process.env.OPENAI_API_KEY ?? "",
  anthropicApiKey: process.env.ANTHROPIC_API_KEY ?? "",
  // Authenticated Web 2.0 Platforms
  mediumApiToken: process.env.MEDIUM_API_TOKEN ?? "",
  mediumAuthorId: process.env.MEDIUM_AUTHOR_ID ?? "",
  bloggerRefreshToken: process.env.BLOGGER_REFRESH_TOKEN ?? "",
  bloggerClientId: process.env.BLOGGER_CLIENT_ID ?? "",
  bloggerClientSecret: process.env.BLOGGER_CLIENT_SECRET ?? "",
  bloggerBlogId: process.env.BLOGGER_BLOG_ID ?? "",
  wpComAccessToken: process.env.WPCOM_ACCESS_TOKEN ?? "",
  wpComSiteId: process.env.WPCOM_SITE_ID ?? "",
};
