/**
 * Expanded Ranking Factors — 120+ additional factors
 * These are merged into the main RANKING_FACTORS array
 */
import type { RankingFactor } from "./google-algorithm-intelligence";

export const EXPANDED_DOMAIN_FACTORS: RankingFactor[] = [
  {
    id: 10001, name: "WhoIs Domain Publicly Available", category: "domain",
    description: "Publicly available WhoIs data can signal legitimacy and transparency",
    impact: "minimal", exploitable: false, fastRankRelevance: 1, confirmed: false,
  },
  {
    id: 10002, name: "Domain Name Includes Target Geo", category: "domain",
    description: "Domain containing city/country name helps local SEO ranking",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Register domains with target city names for local gambling keywords"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 10003, name: "Domain Registered via Known Spammer Registrar", category: "domain",
    description: "Registrars known for hosting spam may flag domains registered through them",
    impact: "low", exploitable: false, fastRankRelevance: 1, confirmed: false,
    evasionTips: ["Use reputable registrars like Namecheap, GoDaddy, Cloudflare"],
  },
  {
    id: 10004, name: "Domain Extension (TLD) Trust", category: "domain",
    description: ".gov, .edu TLDs have inherent trust; .xyz, .tk may carry spam signals",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Target .edu/.gov subdomains for parasite SEO", "Avoid cheap spam TLDs like .tk, .ml"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 10005, name: "Domain Previously Penalized", category: "domain",
    description: "Domains with penalty history carry that stigma even after ownership change",
    impact: "high", exploitable: false, fastRankRelevance: 1, confirmed: true,
    penaltyTriggers: ["Buying expired domains with manual action history"],
    evasionTips: ["Always check domain penalty history before acquisition", "Use Wayback Machine to verify clean history"],
  },
  {
    id: 10006, name: "Domain Expiration Date", category: "domain",
    description: "Domains renewed for 3+ years signal long-term commitment vs 1-year doorway domains",
    impact: "minimal", exploitable: false, fastRankRelevance: 1, confirmed: true,
  },
  {
    id: 10007, name: "Hyphenated Domain", category: "domain",
    description: "Hyphens in domain name can be a spam indicator and reduce trust",
    impact: "low", exploitable: false, fastRankRelevance: 1, confirmed: false,
    evasionTips: ["Avoid hyphens in domain names for target sites"],
  },
];

export const EXPANDED_PAGE_LEVEL_FACTORS: RankingFactor[] = [
  {
    id: 20001, name: "Image Optimization (Alt Tags)", category: "page_level",
    description: "Image alt text provides relevancy signal and helps image search ranking",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Include keyword in image alt tags", "Use descriptive alt text for all images on parasite pages"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 20002, name: "Image Recency", category: "page_level",
    description: "Recently uploaded images may get preference in image search results",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Upload fresh images with each content update"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 20003, name: "Number of Images", category: "page_level",
    description: "Pages with more images correlate with higher rankings; signals content richness",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Include 3-5 relevant images per parasite page", "Use infographics and charts"],
    fastRankRelevance: 4, confirmed: false,
  },
  {
    id: 20004, name: "Image File Size and Compression", category: "page_level",
    description: "Optimized images improve page speed which is a confirmed ranking factor",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Compress images to WebP format", "Keep images under 100KB"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 20005, name: "HTML Errors/W3C Validation", category: "page_level",
    description: "Lots of HTML errors may indicate low-quality site; W3C validation as quality signal",
    impact: "low", exploitable: false, fastRankRelevance: 2, confirmed: false,
  },
  {
    id: 20006, name: "URL Length", category: "page_level",
    description: "Shorter URLs tend to rank better; excessively long URLs may hurt rankings",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Keep URL slugs short and keyword-focused", "Avoid parameter-heavy URLs"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 20007, name: "URL Path", category: "page_level",
    description: "Pages closer to homepage (fewer directory levels) may get more authority",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Deploy parasite content at root level when possible"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 20008, name: "Human Editors/Quality Raters", category: "page_level",
    description: "Google employs quality raters whose feedback influences algorithm updates",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
  },
  {
    id: 20009, name: "Page Category", category: "page_level",
    description: "Category page appears in is a relevancy signal; gambling in entertainment vs finance",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Categorize parasite content under relevant topics", "Use appropriate platform categories"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 20010, name: "WordPress Tags", category: "page_level",
    description: "Tags on WordPress/CMS platforms provide additional relevancy signals",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Use keyword-rich tags on WordPress parasite posts"],
    fastRankRelevance: 2, confirmed: false,
  },
  {
    id: 20011, name: "Keyword in First 100 Words", category: "page_level",
    description: "Having keyword appear in first 100 words of content is first-order relevancy signal",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Always include primary keyword in opening paragraph", "Place keyword naturally in first 2 sentences"],
    fastRankRelevance: 8, confirmed: true,
  },
  {
    id: 20012, name: "Grammar and Spelling", category: "page_level",
    description: "Proper grammar and spelling are quality signals; errors indicate low-quality content",
    impact: "medium", exploitable: false, fastRankRelevance: 4, confirmed: false,
    evasionTips: ["Always run AI content through grammar check", "Ensure Thai content uses proper grammar"],
  },
  {
    id: 20013, name: "Content Readability Level", category: "page_level",
    description: "Content readable at appropriate level for audience; Flesch-Kincaid score matters",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Target grade 7-8 reading level for broad audience", "Use clear, simple language"],
    fastRankRelevance: 4, confirmed: false,
  },
  {
    id: 20014, name: "Affiliate Links", category: "page_level",
    description: "Too many affiliate links can be a thin affiliate site signal",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
    penaltyTriggers: ["Pages with excessive affiliate links and thin content"],
    evasionTips: ["Limit affiliate links", "Add substantial original content around links"],
  },
  {
    id: 20015, name: "Bullet Points and Numbered Lists", category: "page_level",
    description: "Formatted lists help readability and can trigger featured snippets",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Include numbered lists for step-by-step content", "Use bullet points for feature comparisons"],
    fastRankRelevance: 6, confirmed: true,
  },
  {
    id: 20016, name: "Priority in Sitemap", category: "page_level",
    description: "Priority set in sitemap.xml may influence crawl priority",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Set high priority for target pages in sitemap"],
    fastRankRelevance: 2, confirmed: false,
  },
  {
    id: 20017, name: "Too Many Outbound Links", category: "page_level",
    description: "Pages with excessive outbound links may leak PageRank and look spammy",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
    penaltyTriggers: ["50+ outbound links on a single page"],
    evasionTips: ["Limit outbound links to 3-5 per parasite page", "Use nofollow for non-essential links"],
  },
  {
    id: 20018, name: "Page Useful for Other Keywords", category: "page_level",
    description: "If page ranks for multiple keywords, it may get quality boost for all of them",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create comprehensive content covering multiple related keywords", "Target keyword clusters"],
    fastRankRelevance: 6, confirmed: true,
  },
  {
    id: 20019, name: "References and Sources", category: "page_level",
    description: "Citing references and sources signals research quality and E-A-T",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Include 3-5 references to authority sources", "Cite statistics with source links"],
    fastRankRelevance: 5, confirmed: false,
  },
  {
    id: 20020, name: "Rel=Canonical", category: "page_level",
    description: "Proper canonical tag usage prevents duplicate content issues",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Set canonical to preferred URL version", "Prevent duplicate content penalties"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 20021, name: "Chrome Browser Usage Data", category: "page_level",
    description: "Google may use Chrome data to measure page load times and user behavior",
    impact: "high", exploitable: false, fastRankRelevance: 5, confirmed: false,
  },
  {
    id: 20022, name: "Largest Contentful Paint (LCP)", category: "page_level",
    description: "Core Web Vital: measures loading performance. Should be under 2.5 seconds",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Use fast platforms like Telegraph with excellent LCP", "Optimize hero images"],
    fastRankRelevance: 6, confirmed: true,
  },
  {
    id: 20023, name: "First Input Delay (FID) / Interaction to Next Paint (INP)", category: "page_level",
    description: "Core Web Vital: measures interactivity. INP replaced FID in March 2024",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Minimize JavaScript on parasite pages", "Use static HTML content"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 20024, name: "Cumulative Layout Shift (CLS)", category: "page_level",
    description: "Core Web Vital: measures visual stability. Should be under 0.1",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Set image dimensions explicitly", "Avoid dynamic content insertion above fold"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 20025, name: "HTTPS/SSL on Page", category: "page_level",
    description: "HTTPS is confirmed ranking signal; pages without SSL may be flagged as insecure",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["All major parasite platforms use HTTPS by default"],
    fastRankRelevance: 3, confirmed: true,
  },
  {
    id: 20026, name: "AMP (Accelerated Mobile Pages)", category: "page_level",
    description: "AMP pages may get preference in mobile search and news carousel",
    impact: "low", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create AMP versions of key landing pages"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 20027, name: "URL String Matches Keyword", category: "page_level",
    description: "URL containing exact keyword match provides small ranking boost",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Include target keyword in URL slug for all parasite pages"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 20028, name: "Breadcrumb Navigation", category: "page_level",
    description: "Breadcrumbs help Google understand site structure and can appear in SERPs",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Add breadcrumb schema markup to parasite pages"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 20029, name: "Video Content on Page", category: "page_level",
    description: "Pages with embedded video may rank higher; video thumbnails increase CTR in SERPs",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Embed relevant YouTube videos in parasite content", "Create video content for key pages"],
    fastRankRelevance: 5, confirmed: false,
  },
  {
    id: 20030, name: "Content Comprehensiveness", category: "page_level",
    description: "Content that comprehensively covers a topic outranks thin content on same topic",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Use AI to generate comprehensive 2000+ word articles", "Cover all subtopics and related questions"],
    fastRankRelevance: 8, confirmed: true,
  },
  {
    id: 20031, name: "Helpful Content Signal", category: "page_level",
    description: "Google's Helpful Content Update (2022-2024) rewards people-first content over SEO-first content",
    impact: "critical", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Generate content that genuinely answers user questions", "Add personal experience signals", "Include original data/analysis"],
    penaltyTriggers: ["Content clearly written for search engines not people", "Mass AI-generated content without human value"],
    evasionTips: ["Add unique insights and local data", "Include first-person experience language", "Avoid obvious SEO patterns"],
    fastRankRelevance: 9, confirmed: true,
  },
  {
    id: 20032, name: "Content Originality Score", category: "page_level",
    description: "Google's originality detection measures how unique content is compared to existing web pages",
    impact: "critical", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Generate truly unique content per deployment", "Add original data points and local references"],
    penaltyTriggers: ["Content that closely matches existing indexed pages"],
    evasionTips: ["Never use the same template twice", "Vary structure, examples, and writing style"],
    fastRankRelevance: 9, confirmed: true,
  },
  {
    id: 20033, name: "Structured Data (JSON-LD)", category: "page_level",
    description: "JSON-LD structured data helps Google understand page content and enables rich results",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Inject Article, FAQ, HowTo, Review schema via JSON-LD", "Use schema markup injector engine"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 20034, name: "Open Graph and Social Meta Tags", category: "page_level",
    description: "OG tags improve social sharing appearance which drives social signals",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Add OG title, description, image to all parasite pages"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 20035, name: "Page Experience Signals", category: "page_level",
    description: "Combined signal from CWV, mobile-friendliness, HTTPS, no intrusive interstitials",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Deploy on platforms with excellent page experience scores"],
    fastRankRelevance: 6, confirmed: true,
  },
  {
    id: 20036, name: "Intrusive Interstitials", category: "page_level",
    description: "Pages with intrusive popups/interstitials may be demoted in mobile search",
    impact: "medium", exploitable: false, fastRankRelevance: 4, confirmed: true,
    penaltyTriggers: ["Full-screen popups on mobile", "Interstitials blocking content"],
    evasionTips: ["Avoid popups on parasite pages", "Use non-intrusive CTAs"],
  },
  {
    id: 20037, name: "Tab/Accordion Hidden Content", category: "page_level",
    description: "Content hidden in tabs/accordions may be devalued vs visible content",
    impact: "low", exploitable: false, fastRankRelevance: 2, confirmed: false,
    evasionTips: ["Keep important content visible by default"],
  },
  {
    id: 20038, name: "Hreflang Tags for International", category: "page_level",
    description: "Proper hreflang implementation helps rank in correct language/region",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Use hreflang for Thai content targeting Thailand", "Create multi-language versions"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 20039, name: "Content Sentiment/Tone", category: "page_level",
    description: "Google can analyze content sentiment; positive/neutral tone may rank better for informational queries",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Generate content with authoritative, positive tone", "Avoid negative/aggressive language"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 20040, name: "Entity Salience", category: "page_level",
    description: "How prominently entities are mentioned in content affects topical relevance scoring",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Mention target entity prominently throughout content", "Use entity variations and related entities"],
    fastRankRelevance: 7, confirmed: true,
  },
];

export const EXPANDED_SITE_LEVEL_FACTORS: RankingFactor[] = [
  {
    id: 30001, name: "Contact Us Page", category: "site_level",
    description: "Sites with appropriate contact information are more trustworthy per Google Quality Rater Guidelines",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Add contact page to PBN sites", "Include fake but realistic contact info"],
    fastRankRelevance: 3, confirmed: true,
  },
  {
    id: 30002, name: "Site Uptime/Reliability", category: "site_level",
    description: "Frequent downtime or server errors can hurt rankings; Google monitors availability",
    impact: "high", exploitable: false, fastRankRelevance: 4, confirmed: true,
    evasionTips: ["Use reliable hosting for PBN sites", "Monitor uptime"],
  },
  {
    id: 30003, name: "Server Location", category: "site_level",
    description: "Server location influences geo-targeting; Thai server helps rank in Thailand",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Use Thai servers or CDN with Thai edge nodes for target sites"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 30004, name: "Privacy Policy/Terms of Service", category: "site_level",
    description: "Having privacy policy and ToS pages signals legitimate business",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Add privacy policy and ToS to all PBN sites"],
    fastRankRelevance: 2, confirmed: false,
  },
  {
    id: 30005, name: "Duplicate Meta Information", category: "site_level",
    description: "Duplicate title tags and meta descriptions across site pages signal low quality",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
    evasionTips: ["Generate unique titles and descriptions for every page"],
  },
  {
    id: 30006, name: "Breadcrumb Navigation (Site-wide)", category: "site_level",
    description: "Consistent breadcrumb navigation helps Google understand site hierarchy",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Implement breadcrumbs with schema markup on all pages"],
    fastRankRelevance: 3, confirmed: true,
  },
  {
    id: 30007, name: "XML Sitemap", category: "site_level",
    description: "XML sitemap helps Google discover and index pages faster",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Submit sitemaps for PBN sites", "Include all target pages in sitemap"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 30008, name: "Site Has Blog/News Section", category: "site_level",
    description: "Regularly updated blog signals active, maintained site",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Add blog section to PBN sites with regular posts"],
    fastRankRelevance: 4, confirmed: false,
  },
  {
    id: 30009, name: "Site Navigation/User Experience", category: "site_level",
    description: "Easy-to-navigate sites with clear structure rank better",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create clean navigation on PBN sites", "Use logical menu structure"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 30010, name: "Google Search Console Verified", category: "site_level",
    description: "Verified sites in GSC may get crawled more efficiently",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Verify all PBN sites in Search Console", "Submit sitemaps via GSC"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 30011, name: "Google Business Profile", category: "site_level",
    description: "Having a Google Business Profile signals legitimate business for local SEO",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create GBP for target businesses", "Optimize GBP with keywords and photos"],
    fastRankRelevance: 6, confirmed: true,
  },
  {
    id: 30012, name: "Site Reputation/Reviews", category: "site_level",
    description: "Online reviews and reputation signals influence trust and rankings",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Generate positive reviews for target sites", "Build reputation signals across platforms"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 30013, name: "Topical Authority", category: "site_level",
    description: "Sites that comprehensively cover a topic have authority advantage for related queries",
    impact: "critical", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create topical clusters on parasite platforms", "Build 10+ related articles per keyword cluster"],
    fastRankRelevance: 8, confirmed: true,
  },
  {
    id: 30014, name: "Site-Wide Content Quality", category: "site_level",
    description: "Overall content quality of entire site affects individual page rankings",
    impact: "high", exploitable: false, fastRankRelevance: 5, confirmed: true,
    evasionTips: ["Maintain high quality across all PBN pages", "Remove thin/low-quality pages"],
  },
  {
    id: 30015, name: "Robots.txt Configuration", category: "site_level",
    description: "Proper robots.txt ensures Google can crawl important pages",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Configure robots.txt to allow crawling of all target pages"],
    fastRankRelevance: 3, confirmed: true,
  },
  {
    id: 30016, name: "Known Author (Author Authority)", category: "site_level",
    description: "Content by known, authoritative authors ranks better especially for YMYL topics",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create convincing author profiles with credentials", "Link author profiles to social media"],
    fastRankRelevance: 6, confirmed: true,
  },
];

export const EXPANDED_BACKLINK_FACTORS: RankingFactor[] = [
  {
    id: 40001, name: "Link Age", category: "backlink",
    description: "Older links carry more weight than newly built links",
    impact: "medium", exploitable: false, fastRankRelevance: 2, confirmed: true,
  },
  {
    id: 40002, name: "Links from Real Sites vs Splogs", category: "backlink",
    description: "Links from genuine sites with real traffic are more valuable than spam blogs",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Build links from real sites with traffic", "Avoid obvious splog networks"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 40003, name: "Reciprocal Links", category: "backlink",
    description: "Excessive reciprocal linking (A links to B, B links to A) may be devalued",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
    penaltyTriggers: ["Excessive link exchanges between sites"],
    evasionTips: ["Avoid direct reciprocal links", "Use 3-way link schemes instead"],
  },
  {
    id: 40004, name: "User Generated Content Links", category: "backlink",
    description: "Google differentiates between editorial links and UGC links (comments, forums)",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Mix UGC links with editorial links for natural profile", "Use forum/comment links as Tier 2"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 40005, name: "Links from 301 Redirects", category: "backlink",
    description: "Links through 301 redirects pass PageRank but may lose some value",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Use 301 redirects from expired domains to target pages", "Redirect takeover strategy"],
    fastRankRelevance: 6, confirmed: true,
  },
  {
    id: 40006, name: "Backlink Title Attribute", category: "backlink",
    description: "Title attribute on links provides weak relevancy signal",
    impact: "minimal", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Include keyword in link title attributes when possible"],
    fastRankRelevance: 2, confirmed: false,
  },
  {
    id: 40007, name: "Country TLD of Referring Domain", category: "backlink",
    description: "Links from country-specific TLDs help rank in that country",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Build links from .co.th domains for Thai rankings", "Target local TLD backlinks"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 40008, name: "Link Location on Page", category: "backlink",
    description: "Links in content body are more valuable than footer/sidebar/navigation links",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Place links within article body text", "Avoid footer/sidebar link placement"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 40009, name: "Dofollow vs Nofollow", category: "backlink",
    description: "Dofollow links pass PageRank; nofollow links are hints since 2019 (may still pass value)",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Prioritize dofollow links", "Mix in nofollow for natural profile"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 40010, name: "Diversity of Link Types", category: "backlink",
    description: "Natural profiles have mix of text links, image links, redirect links",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Include image links, text links, and redirect links in profile"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 40011, name: "Sponsored/UGC Link Attributes", category: "backlink",
    description: "rel=sponsored and rel=ugc help Google identify paid and user-generated links",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
    evasionTips: ["Avoid rel=sponsored on built links", "Ensure editorial links don't have UGC attribute"],
  },
  {
    id: 40012, name: "Number of Outbound Links on Linking Page", category: "backlink",
    description: "Links from pages with fewer outbound links pass more PageRank per link",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Build links from pages with few outbound links", "Avoid link farm pages"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 40013, name: "Forum Profile Links", category: "backlink",
    description: "Forum profile links are low-value; Google may devalue them",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Use forum profiles as Tier 2/3 links only", "Don't rely on forum links for Tier 1"],
    fastRankRelevance: 2, confirmed: true,
  },
  {
    id: 40014, name: "Guest Post Links", category: "backlink",
    description: "Guest post links are valuable but Google warns against scaled guest posting for links",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Use guest posts on relevant sites", "Vary author names and writing styles"],
    penaltyTriggers: ["Mass guest posting with exact-match anchors"],
    evasionTips: ["Limit to 2-3 guest posts per site", "Use natural anchor text"],
    fastRankRelevance: 6, confirmed: true,
  },
  {
    id: 40015, name: "Homepage Links vs Deep Links", category: "backlink",
    description: "Links to homepage vs inner pages have different weight; natural profiles have both",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Mix homepage and deep page links in link profile"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 40016, name: "Link from .edu or .gov", category: "backlink",
    description: "Links from educational and government domains carry extra trust weight",
    impact: "high", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Find .edu/.gov sites with open posting", "Target scholarship pages, resource pages"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 40017, name: "Negative Link Velocity", category: "backlink",
    description: "Decreasing link acquisition rate signals declining popularity",
    impact: "medium", exploitable: false, fastRankRelevance: 4, confirmed: true,
    evasionTips: ["Maintain consistent link building pace", "Don't stop link building after initial push"],
  },
  {
    id: 40018, name: "Links from Hub Pages", category: "backlink",
    description: "Links from pages considered hubs/authorities on a topic carry extra weight (Hilltop Algorithm)",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Build links from known resource/hub pages in gambling niche"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 40019, name: "Link from Competitor", category: "backlink",
    description: "Links from pages ranking for the same keyword are especially valuable",
    impact: "high", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Identify competitor pages and build links from same sources"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 40020, name: "Social Shares of Linking Page", category: "backlink",
    description: "Links from highly-shared pages may carry more weight",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Build links from viral/popular content", "Boost social shares of linking pages"],
    fastRankRelevance: 4, confirmed: false,
  },
];

export const EXPANDED_USER_INTERACTION_FACTORS: RankingFactor[] = [
  {
    id: 50001, name: "Repeat Traffic", category: "user_interaction",
    description: "Sites with returning visitors signal quality; Google may use Chrome data",
    impact: "medium", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Drive repeat visits via social campaigns", "Create bookmark-worthy content"],
    fastRankRelevance: 4, confirmed: false,
  },
  {
    id: 50002, name: "Blocked Sites (Chrome/Personal Blocklist)", category: "user_interaction",
    description: "Sites blocked by users in Chrome may get demoted for those users and potentially broadly",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: false,
    evasionTips: ["Create quality content that users don't want to block"],
  },
  {
    id: 50003, name: "Google Bookmarks/Favorites", category: "user_interaction",
    description: "Sites bookmarked in Chrome may get ranking boost for that user and potentially broadly",
    impact: "low", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Encourage bookmarking via CTAs"],
    fastRankRelevance: 2, confirmed: false,
  },
  {
    id: 50004, name: "Number of Comments", category: "user_interaction",
    description: "Pages with many comments signal engagement and community interest",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Generate fake comments on parasite pages", "Encourage real engagement"],
    fastRankRelevance: 4, confirmed: false,
  },
  {
    id: 50005, name: "Time on Site (Session Duration)", category: "user_interaction",
    description: "Longer session duration signals quality content and satisfied users",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create long, engaging content", "Add internal links to keep users browsing"],
    fastRankRelevance: 6, confirmed: false,
  },
  {
    id: 50006, name: "Search Result Click-Through Pattern", category: "user_interaction",
    description: "If users consistently skip your result for others, ranking may drop",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Optimize title/description for maximum CTR", "Use power words and numbers"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 50007, name: "Long Click vs Short Click", category: "user_interaction",
    description: "Long clicks (user stays on page) are positive; short clicks (quick return) are negative",
    impact: "critical", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create content that satisfies search intent immediately", "Hook readers in first paragraph"],
    fastRankRelevance: 8, confirmed: true,
  },
  {
    id: 50008, name: "Query Refinement After Click", category: "user_interaction",
    description: "If user refines their search after visiting your page, it signals unsatisfied intent",
    impact: "high", exploitable: false, fastRankRelevance: 6, confirmed: true,
    evasionTips: ["Ensure content fully answers the search query", "Cover related questions"],
  },
];

export const EXPANDED_SPECIAL_ALGORITHM_FACTORS: RankingFactor[] = [
  {
    id: 60001, name: "Query Deserves Diversity (QDD)", category: "special_algorithm",
    description: "Google adds diversity to SERPs for ambiguous queries; shows different interpretations",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Target different angles of ambiguous keywords", "Create content for each interpretation"],
    fastRankRelevance: 6, confirmed: true,
  },
  {
    id: 60002, name: "Transactional vs Informational Searches", category: "special_algorithm",
    description: "Google shows different result types based on search intent classification",
    impact: "critical", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Match content format to search intent", "Create transactional pages for buy-intent keywords"],
    fastRankRelevance: 9, confirmed: true,
  },
  {
    id: 60003, name: "Local Search Results", category: "special_algorithm",
    description: "Google shows local results for queries with local intent; local pack dominates SERPs",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Optimize for local keywords", "Create location-specific parasite content"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 60004, name: "Google News Box", category: "special_algorithm",
    description: "Certain keywords trigger Google News results in SERPs",
    impact: "high", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Publish news-style content on news-approved platforms", "Time content with trending events"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 60005, name: "Shopping Results", category: "special_algorithm",
    description: "Product-related queries trigger Google Shopping results",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
  },
  {
    id: 60006, name: "Image Results in Web Search", category: "special_algorithm",
    description: "Certain queries trigger image pack in web results; optimized images can capture this",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Optimize images with keyword-rich filenames and alt text", "Create infographics"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 60007, name: "People Also Ask (PAA)", category: "special_algorithm",
    description: "PAA boxes appear for most queries; content formatted as Q&A can capture these",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Include FAQ sections in all content", "Format answers in 40-60 word paragraphs"],
    fastRankRelevance: 8, confirmed: true,
  },
  {
    id: 60008, name: "Knowledge Graph/Panel", category: "special_algorithm",
    description: "Google's Knowledge Graph provides entity information directly in SERPs",
    impact: "high", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Build entity presence across multiple platforms", "Use structured data for entity info"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 60009, name: "SafeSearch Filter", category: "special_algorithm",
    description: "Content flagged as adult/explicit is filtered from SafeSearch results",
    impact: "high", exploitable: false, fastRankRelevance: 5, confirmed: true,
    evasionTips: ["Avoid explicit content on parasite pages", "Keep gambling content informational"],
  },
  {
    id: 60010, name: "DMCA Complaints", category: "special_algorithm",
    description: "Pages with legitimate DMCA complaints get demoted in search results",
    impact: "high", exploitable: false, fastRankRelevance: 4, confirmed: true,
    evasionTips: ["Never use copyrighted content", "Generate original content only"],
  },
  {
    id: 60011, name: "Domain Diversity in SERPs", category: "special_algorithm",
    description: "Google limits results from same domain; typically max 2 results per domain per query",
    impact: "high", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Deploy across multiple platforms to capture multiple SERP positions"],
    fastRankRelevance: 8, confirmed: true,
  },
  {
    id: 60012, name: "Navigational Searches", category: "special_algorithm",
    description: "For navigational queries (brand searches), the brand's site dominates results",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Build brand signals to capture navigational queries"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 60013, name: "SpamBrain AI", category: "special_algorithm",
    description: "Google's AI-based spam detection system that identifies and demotes spam content",
    impact: "critical", exploitable: false, fastRankRelevance: 10, confirmed: true,
    penaltyTriggers: ["AI-detected spam patterns", "Manipulative link schemes", "Auto-generated spam content"],
    evasionTips: ["Make content indistinguishable from human-written", "Avoid detectable patterns", "Vary everything"],
  },
  {
    id: 60014, name: "Passage Ranking", category: "special_algorithm",
    description: "Google can rank specific passages within a page, not just the whole page",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Structure content with clear, self-contained sections", "Answer specific questions in dedicated paragraphs"],
    fastRankRelevance: 7, confirmed: true,
  },
  {
    id: 60015, name: "MUM (Multitask Unified Model)", category: "special_algorithm",
    description: "Google's MUM understands complex queries across languages and modalities",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create multi-format content (text + images + video)", "Cover topics comprehensively"],
    fastRankRelevance: 6, confirmed: true,
  },
];

export const EXPANDED_BRAND_SIGNAL_FACTORS: RankingFactor[] = [
  {
    id: 70001, name: "Official Social Media Profiles", category: "brand_signal",
    description: "Having active social media profiles signals legitimate brand",
    impact: "medium", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Create social profiles for target brands", "Maintain active posting schedule"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 70002, name: "Brand Mentioned on News Sites", category: "brand_signal",
    description: "Brand mentions on major news sites signal authority and trust",
    impact: "high", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Get brand mentioned on news aggregators", "Create press releases"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 70003, name: "Brand Has Physical Office (Local SEO)", category: "brand_signal",
    description: "Brands with verified physical locations get local SEO benefits",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Create Google Business Profile with address", "Use virtual office addresses"],
    fastRankRelevance: 4, confirmed: true,
  },
  {
    id: 70004, name: "Brand is Entity in Knowledge Graph", category: "brand_signal",
    description: "Brands recognized as entities in Google's Knowledge Graph get significant trust boost",
    impact: "high", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Build Wikipedia page", "Create Wikidata entry", "Build entity presence across platforms"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 70005, name: "Competitor Brand Searches", category: "brand_signal",
    description: "If users search for your brand after searching for competitors, it signals relevance",
    impact: "medium", exploitable: true, exploitDifficulty: "hard",
    exploitTactics: ["Run comparison content targeting competitor brand + your brand"],
    fastRankRelevance: 4, confirmed: false,
  },
  {
    id: 70006, name: "Social Media Follower Count", category: "brand_signal",
    description: "Large social following signals brand authority and popularity",
    impact: "medium", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Build social following through paid promotion", "Cross-promote across platforms"],
    fastRankRelevance: 3, confirmed: false,
  },
  {
    id: 70007, name: "LinkedIn Company Page", category: "brand_signal",
    description: "Having a LinkedIn company page signals legitimate business",
    impact: "low", exploitable: true, exploitDifficulty: "easy",
    exploitTactics: ["Create LinkedIn pages for target brands"],
    fastRankRelevance: 2, confirmed: false,
  },
  {
    id: 70008, name: "Tax/Business Registration", category: "brand_signal",
    description: "Registered businesses with tax IDs signal legitimacy to Google",
    impact: "medium", exploitable: false, fastRankRelevance: 2, confirmed: false,
  },
];

export const EXPANDED_ON_SITE_SPAM_FACTORS: RankingFactor[] = [
  {
    id: 80001, name: "Cloaking", category: "on_site_spam",
    description: "Showing different content to Googlebot vs users is a severe violation",
    impact: "critical", exploitable: false, fastRankRelevance: 1, confirmed: true,
    penaltyTriggers: ["Different content served to Googlebot", "IP-based content switching"],
    evasionTips: ["Never cloak content", "Show same content to all users and bots"],
  },
  {
    id: 80002, name: "Doorway Pages", category: "on_site_spam",
    description: "Pages created solely to rank for specific queries that funnel users to another page",
    impact: "critical", exploitable: false, fastRankRelevance: 2, confirmed: true,
    penaltyTriggers: ["Multiple pages targeting same keyword with redirect", "Thin pages funneling to money page"],
    evasionTips: ["Make each page genuinely useful", "Don't redirect all traffic to one page"],
  },
  {
    id: 80003, name: "Sneaky Redirects", category: "on_site_spam",
    description: "Redirecting users to different page than what Googlebot sees",
    impact: "critical", exploitable: false, fastRankRelevance: 1, confirmed: true,
    penaltyTriggers: ["JavaScript redirects to different content", "Mobile-only redirects to spam"],
    evasionTips: ["Use clean 301 redirects only", "Same destination for all users"],
  },
  {
    id: 80004, name: "Hidden Text/Links", category: "on_site_spam",
    description: "Text/links invisible to users but visible to search engines (white text on white bg, CSS hidden)",
    impact: "critical", exploitable: false, fastRankRelevance: 1, confirmed: true,
    penaltyTriggers: ["CSS display:none with keyword text", "Font-size:0 text", "Text same color as background"],
    evasionTips: ["Never hide text or links", "All content must be visible to users"],
  },
  {
    id: 80005, name: "Keyword Stuffing", category: "on_site_spam",
    description: "Unnaturally repeating keywords in content, meta tags, or alt text",
    impact: "critical", exploitable: false, fastRankRelevance: 7, confirmed: true,
    penaltyTriggers: ["Keyword density >5%", "Repeated keywords in meta tags", "Keyword lists in footer"],
    evasionTips: ["Keep keyword density at 2-3%", "Use natural language", "Include synonyms and variations"],
  },
  {
    id: 80006, name: "Ads Above the Fold", category: "on_site_spam",
    description: "Page Layout Algorithm penalizes pages with too many ads above the fold",
    impact: "high", exploitable: false, fastRankRelevance: 4, confirmed: true,
    penaltyTriggers: ["Excessive ads pushing content below fold", "Interstitial ads on mobile"],
    evasionTips: ["Keep content above fold", "Minimize ad placement on parasite pages"],
  },
  {
    id: 80007, name: "Hiding Affiliate Links", category: "on_site_spam",
    description: "Attempting to disguise affiliate links through redirects or cloaking",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
    penaltyTriggers: ["Cloaked affiliate links", "Deceptive redirect chains"],
    evasionTips: ["Use transparent affiliate disclosures", "Don't cloak affiliate URLs"],
  },
  {
    id: 80008, name: "Spammy Structured Data", category: "on_site_spam",
    description: "Fake or misleading structured data markup (fake reviews, wrong schema type)",
    impact: "high", exploitable: false, fastRankRelevance: 5, confirmed: true,
    penaltyTriggers: ["Fake review ratings in schema", "Schema not matching page content"],
    evasionTips: ["Only use schema that accurately represents page content"],
  },
  {
    id: 80009, name: "Thin Content with Affiliate Links", category: "on_site_spam",
    description: "Pages with little original content that primarily exist to drive affiliate clicks",
    impact: "critical", exploitable: false, fastRankRelevance: 6, confirmed: true,
    penaltyTriggers: ["<300 words with multiple affiliate links", "No original content around affiliate links"],
    evasionTips: ["Add 1000+ words of original content around any affiliate links"],
  },
  {
    id: 80010, name: "Scraped Content", category: "on_site_spam",
    description: "Content copied/scraped from other websites without adding value",
    impact: "critical", exploitable: false, fastRankRelevance: 8, confirmed: true,
    penaltyTriggers: ["Exact copy of indexed content", "Automated scraping and republishing"],
    evasionTips: ["Always generate original AI content", "Never scrape and republish"],
  },
  {
    id: 80011, name: "Excessive 404 Pages", category: "on_site_spam",
    description: "Too many 404 errors signal poorly maintained site",
    impact: "medium", exploitable: false, fastRankRelevance: 2, confirmed: false,
    evasionTips: ["Monitor and fix broken links", "Implement proper 301 redirects"],
  },
  {
    id: 80012, name: "Hacked Site Warning", category: "on_site_spam",
    description: "Google flags hacked sites and removes them from search results",
    impact: "critical", exploitable: false, fastRankRelevance: 1, confirmed: true,
    penaltyTriggers: ["Malware detected on site", "Injected spam content"],
    evasionTips: ["Keep sites secure", "Monitor for unauthorized changes"],
  },
];

export const EXPANDED_OFF_SITE_SPAM_FACTORS: RankingFactor[] = [
  {
    id: 90001, name: "Link Schemes", category: "off_site_spam",
    description: "Any links intended to manipulate PageRank or site's ranking violate Google guidelines",
    impact: "critical", exploitable: false, fastRankRelevance: 8, confirmed: true,
    penaltyTriggers: ["Buying/selling links that pass PageRank", "Excessive link exchanges", "Large-scale article marketing"],
    evasionTips: ["Make link building look organic", "Vary methods and timing", "Don't leave obvious patterns"],
  },
  {
    id: 90002, name: "Paid Links", category: "off_site_spam",
    description: "Google actively detects and penalizes paid links that pass PageRank",
    impact: "critical", exploitable: false, fastRankRelevance: 7, confirmed: true,
    penaltyTriggers: ["Links with obvious paid patterns", "Advertorial links without nofollow"],
    evasionTips: ["Make paid links look editorial", "Use intermediary platforms"],
  },
  {
    id: 90003, name: "Negative SEO Attack", category: "off_site_spam",
    description: "Competitors building spammy links to your site to trigger penalty",
    impact: "high", exploitable: true, exploitDifficulty: "moderate",
    exploitTactics: ["Build toxic links to competitor sites", "Use disavow tool defensively"],
    fastRankRelevance: 5, confirmed: true,
  },
  {
    id: 90004, name: "Disavow File", category: "off_site_spam",
    description: "Google's disavow tool lets sites distance themselves from toxic backlinks",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
  },
  {
    id: 90005, name: "Link Farm Participation", category: "off_site_spam",
    description: "Sites participating in link farms (networks of sites linking to each other) get penalized",
    impact: "critical", exploitable: false, fastRankRelevance: 6, confirmed: true,
    penaltyTriggers: ["Membership in known link farm networks", "Automated link exchange systems"],
    evasionTips: ["Avoid known link farm networks", "Build links manually from diverse sources"],
  },
  {
    id: 90006, name: "Widget Links", category: "off_site_spam",
    description: "Links embedded in widgets distributed across many sites are devalued",
    impact: "medium", exploitable: false, fastRankRelevance: 3, confirmed: true,
    penaltyTriggers: ["Keyword-rich widget links across many sites"],
    evasionTips: ["Avoid widget-based link building"],
  },
  {
    id: 90007, name: "Links from Press Releases", category: "off_site_spam",
    description: "Links from press release distribution sites are largely devalued",
    impact: "low", exploitable: false, fastRankRelevance: 2, confirmed: true,
    evasionTips: ["Don't rely on press release links for SEO"],
  },
  {
    id: 90008, name: "Manual Penalty (Manual Action)", category: "off_site_spam",
    description: "Google's webspam team can manually penalize sites; shown in Search Console",
    impact: "critical", exploitable: false, fastRankRelevance: 10, confirmed: true,
    penaltyTriggers: ["Obvious manipulation detected by human reviewer", "Reports from competitors"],
    evasionTips: ["Stay below detection threshold", "Don't be too aggressive too fast"],
  },
  {
    id: 90009, name: "Selling Links", category: "off_site_spam",
    description: "Sites caught selling links lose their own rankings and link value",
    impact: "critical", exploitable: false, fastRankRelevance: 5, confirmed: true,
    penaltyTriggers: ["Advertising link sales", "Pattern of outbound paid links"],
    evasionTips: ["Don't sell links from PBN sites openly"],
  },
  {
    id: 90010, name: "Google Disavow Tool Effectiveness", category: "off_site_spam",
    description: "Properly using disavow tool can recover from link-based penalties",
    impact: "high", exploitable: false, fastRankRelevance: 3, confirmed: true,
  },
  {
    id: 90011, name: "Reconsideration Request", category: "off_site_spam",
    description: "Successful reconsideration request can lift manual penalties",
    impact: "high", exploitable: false, fastRankRelevance: 2, confirmed: true,
  },
  {
    id: 90012, name: "Temporary Link Schemes", category: "off_site_spam",
    description: "Building links temporarily then removing them is detected by Google",
    impact: "medium", exploitable: false, fastRankRelevance: 4, confirmed: true,
    penaltyTriggers: ["Links appearing and disappearing in patterns"],
    evasionTips: ["Keep built links permanent", "Don't remove links after ranking"],
  },
];
